// Generated by: supabase gen types typescript --linked > src/lib/types/database.types.ts
// (here via the Supabase MCP generate_typescript_types tool). Do not hand-edit —
// regenerate after every migration. See docs/architecture/DATA_MODEL.md for the
// schema this reflects.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
	// Allows to automatically instantiate createClient with right options
	// instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
	__InternalSupabase: {
		PostgrestVersion: '14.15';
	};
	public: {
		Tables: {
			app_settings: {
				Row: {
					key: string;
					updated_at: string | null;
					updated_by: string | null;
					value: Json;
				};
				Insert: {
					key: string;
					updated_at?: string | null;
					updated_by?: string | null;
					value: Json;
				};
				Update: {
					key?: string;
					updated_at?: string | null;
					updated_by?: string | null;
					value?: Json;
				};
				Relationships: [
					{
						foreignKeyName: 'app_settings_updated_by_fkey';
						columns: ['updated_by'];
						isOneToOne: false;
						referencedRelation: 'profiles';
						referencedColumns: ['id'];
					}
				];
			};
			audit_logs: {
				Row: {
					action: string;
					actor_id: string | null;
					after_data: Json | null;
					before_data: Json | null;
					created_at: string | null;
					entity_id: string | null;
					entity_type: string;
					id: string;
					metadata: Json | null;
				};
				Insert: {
					action: string;
					actor_id?: string | null;
					after_data?: Json | null;
					before_data?: Json | null;
					created_at?: string | null;
					entity_id?: string | null;
					entity_type: string;
					id?: string;
					metadata?: Json | null;
				};
				Update: {
					action?: string;
					actor_id?: string | null;
					after_data?: Json | null;
					before_data?: Json | null;
					created_at?: string | null;
					entity_id?: string | null;
					entity_type?: string;
					id?: string;
					metadata?: Json | null;
				};
				Relationships: [
					{
						foreignKeyName: 'audit_logs_actor_id_fkey';
						columns: ['actor_id'];
						isOneToOne: false;
						referencedRelation: 'profiles';
						referencedColumns: ['id'];
					}
				];
			};
			games: {
				Row: {
					created_at: string | null;
					current_question_id: string | null;
					current_round_id: string | null;
					finished_at: string | null;
					host_id: string | null;
					id: string;
					pin: string;
					started_at: string | null;
					status: string;
					title: string;
				};
				Insert: {
					created_at?: string | null;
					current_question_id?: string | null;
					current_round_id?: string | null;
					finished_at?: string | null;
					host_id?: string | null;
					id?: string;
					pin: string;
					started_at?: string | null;
					status?: string;
					title: string;
				};
				Update: {
					created_at?: string | null;
					current_question_id?: string | null;
					current_round_id?: string | null;
					finished_at?: string | null;
					host_id?: string | null;
					id?: string;
					pin?: string;
					started_at?: string | null;
					status?: string;
					title?: string;
				};
				Relationships: [
					{
						foreignKeyName: 'games_current_question_id_fkey';
						columns: ['current_question_id'];
						isOneToOne: false;
						referencedRelation: 'questions';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'games_current_round_id_fkey';
						columns: ['current_round_id'];
						isOneToOne: false;
						referencedRelation: 'rounds';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'games_host_id_fkey';
						columns: ['host_id'];
						isOneToOne: false;
						referencedRelation: 'profiles';
						referencedColumns: ['id'];
					}
				];
			};
			profiles: {
				Row: {
					created_at: string | null;
					display_name: string;
					id: string;
					role_id: number;
				};
				Insert: {
					created_at?: string | null;
					display_name: string;
					id: string;
					role_id?: number;
				};
				Update: {
					created_at?: string | null;
					display_name?: string;
					id?: string;
					role_id?: number;
				};
				Relationships: [
					{
						foreignKeyName: 'profiles_role_id_fkey';
						columns: ['role_id'];
						isOneToOne: false;
						referencedRelation: 'roles';
						referencedColumns: ['id'];
					}
				];
			};
			question_choice_options: {
				Row: {
					id: string;
					image_url: string | null;
					is_correct: boolean;
					option_text: string;
					order_index: number;
					question_id: string | null;
				};
				Insert: {
					id?: string;
					image_url?: string | null;
					is_correct?: boolean;
					option_text: string;
					order_index: number;
					question_id?: string | null;
				};
				Update: {
					id?: string;
					image_url?: string | null;
					is_correct?: boolean;
					option_text?: string;
					order_index?: number;
					question_id?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: 'question_choice_options_question_id_fkey';
						columns: ['question_id'];
						isOneToOne: false;
						referencedRelation: 'questions';
						referencedColumns: ['id'];
					}
				];
			};
			question_ordering_items: {
				Row: {
					correct_position: number;
					id: string;
					item_text: string;
					question_id: string | null;
				};
				Insert: {
					correct_position: number;
					id?: string;
					item_text: string;
					question_id?: string | null;
				};
				Update: {
					correct_position?: number;
					id?: string;
					item_text?: string;
					question_id?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: 'question_ordering_items_question_id_fkey';
						columns: ['question_id'];
						isOneToOne: false;
						referencedRelation: 'questions';
						referencedColumns: ['id'];
					}
				];
			};
			question_slider_config: {
				Row: {
					correct_value: number;
					max_value: number;
					min_value: number;
					question_id: string;
					step: number;
					tolerance: number;
				};
				Insert: {
					correct_value: number;
					max_value: number;
					min_value: number;
					question_id: string;
					step?: number;
					tolerance?: number;
				};
				Update: {
					correct_value?: number;
					max_value?: number;
					min_value?: number;
					question_id?: string;
					step?: number;
					tolerance?: number;
				};
				Relationships: [
					{
						foreignKeyName: 'question_slider_config_question_id_fkey';
						columns: ['question_id'];
						isOneToOne: true;
						referencedRelation: 'questions';
						referencedColumns: ['id'];
					}
				];
			};
			question_types: {
				Row: {
					code: string;
					description: string | null;
					id: number;
					label: string;
					max_options: number | null;
					min_options: number | null;
				};
				Insert: {
					code: string;
					description?: string | null;
					id: number;
					label: string;
					max_options?: number | null;
					min_options?: number | null;
				};
				Update: {
					code?: string;
					description?: string | null;
					id?: number;
					label?: string;
					max_options?: number | null;
					min_options?: number | null;
				};
				Relationships: [];
			};
			questions: {
				Row: {
					created_at: string | null;
					created_by: string | null;
					id: string;
					image_url: string | null;
					last_used_at: string | null;
					points: number | null;
					points_decay: boolean | null;
					points_multiplier: number | null;
					prompt: string;
					question_type_id: number;
					theme_id: string | null;
					time_limit_seconds: number | null;
				};
				Insert: {
					created_at?: string | null;
					created_by?: string | null;
					id?: string;
					image_url?: string | null;
					last_used_at?: string | null;
					points?: number | null;
					points_decay?: boolean | null;
					points_multiplier?: number | null;
					prompt: string;
					question_type_id: number;
					theme_id?: string | null;
					time_limit_seconds?: number | null;
				};
				Update: {
					created_at?: string | null;
					created_by?: string | null;
					id?: string;
					image_url?: string | null;
					last_used_at?: string | null;
					points?: number | null;
					points_decay?: boolean | null;
					points_multiplier?: number | null;
					prompt?: string;
					question_type_id?: number;
					theme_id?: string | null;
					time_limit_seconds?: number | null;
				};
				Relationships: [
					{
						foreignKeyName: 'questions_created_by_fkey';
						columns: ['created_by'];
						isOneToOne: false;
						referencedRelation: 'profiles';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'questions_question_type_id_fkey';
						columns: ['question_type_id'];
						isOneToOne: false;
						referencedRelation: 'question_types';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'questions_theme_id_fkey';
						columns: ['theme_id'];
						isOneToOne: false;
						referencedRelation: 'themes';
						referencedColumns: ['id'];
					}
				];
			};
			roles: {
				Row: {
					code: string;
					id: number;
					label: string;
				};
				Insert: {
					code: string;
					id: number;
					label: string;
				};
				Update: {
					code?: string;
					id?: number;
					label?: string;
				};
				Relationships: [];
			};
			round_questions: {
				Row: {
					order_index: number;
					question_id: string;
					round_id: string;
					used_at: string | null;
				};
				Insert: {
					order_index: number;
					question_id: string;
					round_id: string;
					used_at?: string | null;
				};
				Update: {
					order_index?: number;
					question_id?: string;
					round_id?: string;
					used_at?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: 'round_questions_question_id_fkey';
						columns: ['question_id'];
						isOneToOne: false;
						referencedRelation: 'questions';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'round_questions_round_id_fkey';
						columns: ['round_id'];
						isOneToOne: false;
						referencedRelation: 'rounds';
						referencedColumns: ['id'];
					}
				];
			};
			rounds: {
				Row: {
					game_id: string | null;
					id: string;
					order_index: number;
					title: string;
				};
				Insert: {
					game_id?: string | null;
					id?: string;
					order_index: number;
					title: string;
				};
				Update: {
					game_id?: string | null;
					id?: string;
					order_index?: number;
					title?: string;
				};
				Relationships: [
					{
						foreignKeyName: 'rounds_game_id_fkey';
						columns: ['game_id'];
						isOneToOne: false;
						referencedRelation: 'games';
						referencedColumns: ['id'];
					}
				];
			};
			teams: {
				Row: {
					color: string | null;
					device_token: string;
					game_id: string | null;
					id: string;
					joined_at: string | null;
					name: string;
					total_score: number | null;
				};
				Insert: {
					color?: string | null;
					device_token: string;
					game_id?: string | null;
					id?: string;
					joined_at?: string | null;
					name: string;
					total_score?: number | null;
				};
				Update: {
					color?: string | null;
					device_token?: string;
					game_id?: string | null;
					id?: string;
					joined_at?: string | null;
					name?: string;
					total_score?: number | null;
				};
				Relationships: [
					{
						foreignKeyName: 'teams_game_id_fkey';
						columns: ['game_id'];
						isOneToOne: false;
						referencedRelation: 'games';
						referencedColumns: ['id'];
					}
				];
			};
			themes: {
				Row: {
					id: string;
					title: string;
				};
				Insert: {
					id?: string;
					title: string;
				};
				Update: {
					id?: string;
					title?: string;
				};
				Relationships: [];
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			current_user_role_id: { Args: never; Returns: number };
			draw_random_questions_for_round: {
				Args: { p_count?: number; p_round_id: string; p_theme_id: string };
				Returns: {
					created_at: string | null;
					created_by: string | null;
					id: string;
					image_url: string | null;
					last_used_at: string | null;
					points: number | null;
					points_decay: boolean | null;
					points_multiplier: number | null;
					prompt: string;
					question_type_id: number;
					theme_id: string | null;
					time_limit_seconds: number | null;
				}[];
				SetofOptions: {
					from: '*';
					to: 'questions';
					isOneToOne: false;
					isSetofReturn: true;
				};
			};
		};
		Enums: {
			[_ in never]: never;
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
	DefaultSchemaTableNameOrOptions extends
		| keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends (DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
				DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
		: never) = never
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
			DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
			Row: infer R;
		}
		? R
		: never
	: DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
		? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
				Row: infer R;
			}
			? R
			: never
		: never;

export type TablesInsert<
	DefaultSchemaTableNameOrOptions extends
		keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
	TableName extends (DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
		: never) = never
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
			Insert: infer I;
		}
		? I
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
		? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
				Insert: infer I;
			}
			? I
			: never
		: never;

export type TablesUpdate<
	DefaultSchemaTableNameOrOptions extends
		keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
	TableName extends (DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
		: never) = never
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
			Update: infer U;
		}
		? U
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
		? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
				Update: infer U;
			}
			? U
			: never
		: never;

export type Enums<
	DefaultSchemaEnumNameOrOptions extends
		keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
	EnumName extends (DefaultSchemaEnumNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
		: never) = never
> = DefaultSchemaEnumNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
	: DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
		? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
		: never;

export type CompositeTypes<
	PublicCompositeTypeNameOrOptions extends
		keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
	CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
		: never) = never
> = PublicCompositeTypeNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
	: PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
		? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
		: never;

export const Constants = {
	public: {
		Enums: {}
	}
} as const;
